apiVersion: v1
kind: Service
metadata: 
  name: yaml-nginx
spec:
  selector:
    app: yaml-nginx
  ports:
    - name: entrypoint
      port: 1337
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata: 
  name: yaml-flask
spec:
  selector:
    app: yaml-flask
  ports:
    - name: entrypoint
      port: 5000
  type: ClusterIP
